"""Add field telegram_file_id to Broadcast model

Revision ID: 307654af6417
Revises: d8cf7cd1f1a5
Create Date: 2025-02-04 20:09:57.596384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307654af6417'
down_revision: Union[str, None] = 'd8cf7cd1f1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('telegram_file_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'telegram_file_id')
    # ### end Alembic commands ###
