"""Add field show_role_name to User

Revision ID: 5bd527fef863
Revises: c5de9b3bf220
Create Date: 2025-02-07 19:11:53.377923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd527fef863'
down_revision: Union[str, None] = 'c5de9b3bf220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_role_name', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_role_name')
    # ### end Alembic commands ###
