"""Add field telegram_file_id_alt to Broadcast

Revision ID: c5de9b3bf220
Revises: 307654af6417
Create Date: 2025-02-07 18:56:55.502169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5de9b3bf220'
down_revision: Union[str, None] = '307654af6417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('telegram_file_id_alt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'telegram_file_id_alt')
    # ### end Alembic commands ###
